# Generated by Django 6.1.1 on 2026-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Two-factor authentication'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
