# Generated by Django 6.1.1 on 2026-09-23 15:11

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIVED', 'Deposit received'), ('DEDUCTION', 'Deduction'), ('REFUND', 'Refund')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_transactions', to='tenants.lease')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.lease')),
            ],
            options={
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GARBAGE', 'Garbage'), ('SECURITY', 'Security'), ('INTERNET', 'Internet'), ('CLEANING', 'Cleaning'), ('LATE_FEE', 'Late fee'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('method', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK', 'Bank transfer'), ('CARD', 'Card'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed / rejected')], default='PENDING', max_length=10)),
                ('internal_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payer_reference', models.CharField(blank=True, max_length=100)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='billing.payment')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water')], max_length=15)),
                ('meter_number', models.CharField(blank=True, max_length=40)),
                ('reading_date', models.DateField(default=datetime.date.today)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price per unit consumed', max_digits=10)),
                ('invoice_item', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoiceitem')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='properties.unit')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('lease', 'period_start'), name='one_live_invoice_per_lease_period'),
        ),
    ]
