# Generated by Django 6.1.1 on 2026-09-23 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Short code, e.g. ROYAL', max_length=20, unique=True)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment block'), ('HOUSE', 'Houses / estate'), ('COMMERCIAL', 'Commercial'), ('MIXED', 'Mixed use'), ('HOSTEL', 'Hostel')], default='APARTMENT', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.FileField(blank=True, upload_to='properties/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_CONSTRUCTION', 'Under construction')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Managers and caretakers who can work on this property.', limit_choices_to={'role__in': ['MANAGER', 'CARETAKER']}, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Block A', max_length=100)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'name'],
                'unique_together': {('property', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='property_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('SINGLE', 'Single room'), ('DOUBLE', 'Double room'), ('STUDIO', 'Studio'), ('1BR', '1 bedroom'), ('2BR', '2 bedroom'), ('3BR', '3 bedroom'), ('SHOP', 'Shop'), ('OFFICE', 'Office')], default='1BR', max_length=10)),
                ('monthly_rent', models.DecimalField(decimal_places=0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under maintenance'), ('VACANT', 'Vacant')], default='AVAILABLE', max_length=15)),
                ('electricity_meter', models.CharField(blank=True, max_length=40)),
                ('water_meter', models.CharField(blank=True, max_length=40)),
                ('photo', models.FileField(blank=True, upload_to='units/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.building')),
            ],
            options={
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
    ]
