# Generated by Django 6.1.1 on 2026-09-24 08:07

import apps.properties.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(storage=apps.properties.models.private_storage, upload_to='property_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
    ]
