# Generated by Django 6.1.1 on 2026-09-24 08:07

import apps.properties.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='registered_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantdocument',
            name='visible_to_tenant',
            field=models.BooleanField(default=True, help_text='Untick for internal documents (e.g. screening notes)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='agreement',
            field=models.FileField(blank=True, storage=apps.properties.models.private_storage, upload_to='leases/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='photo',
            field=models.FileField(blank=True, storage=apps.properties.models.private_storage, upload_to='tenants/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='file',
            field=models.FileField(storage=apps.properties.models.private_storage, upload_to='tenant_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
    ]
