# Generated by Django 6.1.1 on 2026-09-24 08:07

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0002_alter_propertydocument_file'),
        ('tenants', '0002_tenant_registered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('MOVE_IN', 'Move-in'), ('MOVE_OUT', 'Move-out'), ('ROUTINE', 'Routine')], default='ROUTINE', max_length=10)),
                ('inspection_date', models.DateField(default=datetime.date.today)),
                ('overall', models.CharField(choices=[('GOOD', 'Good'), ('MINOR', 'Needs minor repair'), ('MAJOR', 'Needs major repair')], default='GOOD', editable=False, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='tenants.lease')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='properties.unit')),
            ],
            options={
                'ordering': ['-inspection_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=60)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('NEEDS_REPAIR', 'Needs repair'), ('DAMAGED', 'Damaged'), ('NA', 'Not applicable')], default='GOOD', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspection')),
                ('maintenance_request', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='inspections/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
        ),
    ]
